version: '3.8'
services:

  php:
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes: 
      - ./php/volumes:/var/www/html/
    ports:
      - 80:80
    expose:
      - 80
    
  mysql:
    image: mysql:8.0.23
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8083:80
    expose:
      - 8083

  postgres:
    image: postgres:latest
    volumes:
      - ./volums/postgres:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    expose:
      - 5432

  tomcat:
    image: imageName

