version: '3.8'
services: 
  php:
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes: 
      - ./php/volumes:/var/www/html/
    ports:
      - 80:80
    expose:
      - 80

  mysql:
    image: mysql:8.0.23
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
    expose:
      - 3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=user
      - PMA_PASSWORD=user
    expose:
      - 80