version: "4.12"
services:
  apache:
    build:
      context: ./dockerfiles
      dockerfile: apache
    command: "php artisan serve --host 0.0.0.0" 
    volumes:
      - ./volums/apache:/var/www/html
      - ./volums/laravel:/home/first-laravel9
      - ./volums/apache-home:/home  
      - ./volums/apache-config:/etc/apache2
    ports:
      - 80:8000
    expose:
      - 80