services:
  laravel:  
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes: 
      - ./php/volumes:/var/www/html
    tty: true
    ports: 
      - 80:8000
    expose: 
      - 80
  
  mysql:
    image: mysql:8.0.23
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  phpmyadmin: 
    image: phpmyadmin:5.1.3-apache 
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8083:80
    expose:
      - 8083 
